version: "3"
services:
  api:
    depends_on:
      - db
    build: "."
    environment:
      - DB_USER=hncollabcasework
      - DB_NAME=hncollabcasework
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
  db:
    image: postgres
    ports:
      - "10102:5432"
    volumes:
      - ./tmp/data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: "hncollabcasework"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: hncollabcasework
