service: hn-collab-casework-db

provider:
  name: aws
  stage: production
  profile: hackney
  region: eu-west-2

custom:
  DB_HOST:
    Fn::GetAtt: [PostgreSqlRDSInstance, Endpoint.Address]
  DB_PORT:
    Fn::GetAtt: [PostgreSqlRDSInstance, Endpoint.Port]
  DB_INSTANCE_NAME: hncollabcasework-production-db-${file(serverless-vars.js):postfix}
  DB_NAME: ${file(serverless-vars.js):DB_NAME}
  DB_USER: ${file(serverless-vars.js):DB_USER}
  DB_PASSWORD: ${file(serverless-vars.js):DB_PASSWORD}

resources:
  Resources:
    PostgreSqlRDSInstance:
      Type: AWS::RDS::DBInstance
      DeletionPolicy: Retain
      Properties:
        MasterUsername: ${self:custom.DB_USER}
        MasterUserPassword: ${self:custom.DB_PASSWORD}
        AllocatedStorage: 20
        DBName: ${self:custom.DB_NAME}
        DBInstanceClass: db.t2.micro
        DBInstanceIdentifier: ${self:custom.DB_INSTANCE_NAME}
        VPCSecurityGroups:
          - sg-03498eb2bc5287c9a
        DBSubnetGroupName: hackney_apps_db_subnet_20190508161355832000000001
        Engine: postgres
        PubliclyAccessible: true
